- hosts: uninstall_linux_agent
  become: true
  tasks:
    - name: Pull service facts
      service_facts:

    - name: "Remove | Make sure the \"old\" zabbix-agent service stopped"
      service:
        name: "zabbix-agent"
        state: stopped
        enabled: false
      when: |
        ansible_facts.services["zabbix-agent.service"] is defined or
        ansible_facts.services["zabbix-agent"] is defined
    
    - name: "Remove | Make sure the \"old\" zabbix-agent2 service stopped"
      service:
        name: "zabbix-agent2"
        state: stopped
        enabled: false
      when: |
        ansible_facts.services["zabbix-agent2.service"] is defined or
        ansible_facts.services["zabbix-agent2"] is defined
    
    - name: "Remove | Package removal"
      package:
        name: "zabbix-agent"
        state: absent
    
    - name: "Remove | Package removal"
      package:
        name: "zabbix-agent2"
        state: absent    
    
    - name: "Remove | Remove the agent-include-dir"
      file:
        path: /etc/zabbix/zabbix_agentd.d
        state: absent
    
    - name: "Remove | Remove the agent-include-dir"
      file:
        path: /etc/zabbix/zabbix_agent2.d
        state: absent

    - name: "Remove | Remove the config file"
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent
    
    - name: "Remove | Remove the config file"
      file:
        path: /etc/zabbix/zabbix_agent2.conf
        state: absent

