---
#- name: Ping windows host
#  hosts: windows
#  become: false
#  gather_facts: false
#  tasks:
#    - name: test connection
#      ansible.windows.win_ping:
- name: Ping linux host
  hosts: linux
  become: false
  gather_facts: false
  tasks:
    - name: test connection
      wait_for_connection:
         timeout: 30
